<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Application\MathilensERP.Application.csproj" />
    <ProjectReference Include="..\Domain\MathilensERP.Domain.csproj" />
    <ProjectReference Include="..\Shared\MathilensERP.Shared.csproj" />
  </ItemGroup>

</Project>
